name: s3-cache-restore
description: |
  Cache using s3
runs:
  using: node20
  main: main.js

inputs:
  key:
    description: cache key
    required: true
  path:
    description: path to files to cache, use multiline for multiple files
  lookup-only:
    description: If true, only checks if cache entry exists and skips download.
    default: "false"
  fail-on-cache-miss:
    description: Fail the workflow if cache entry is not found.
    default: "false"

  aws-access-key-id:
    description: aws-access-key-id
    required: true
  aws-secret-access-key:
    description: aws-secret-access-key
    required: true
  aws-region:
    description: aws-region
    required: true
  aws-cache-bucket:
    description: aws-cache-bucket
    required: true
outputs:
  cache-hit:
    description: true if a cache is found for this key
